const ROUTES = {
    NOTFOUND: { path: "*", nickname: "404 - Não encontrado"},
    HOME: { path: "/", nickname: "Início"},
    NEWS: { path: "/news/", nickname: "Novidades"},
    LIBRARY: { path: "/library/", nickname: "Biblioteca"},
    MAP: { path: "/map/", nickname: "Mapa"},
    ABOUT: { path: "/about/", nickname: "Sobre"},
    HELP_US: { path: "/helpus/", nickname: "Ajude nos"},
    HALL_OF_FAME: { path: "/halloffame/", nickname: "Hall da Fama"},
    USER_LOGIN: { path: "/user/", nickname: "Acesso"},
    USER_LOGIN_SUBMIT: { path: "/user/login/submit/", nickname: "Acesso"},
    USER_REGISTER: { path: "/user/register/", nickname: "Registro"},
    USER_REGISTER_SUBMIT: { path: "/user/register/submit/", nickname: "Registro"},
    USER_PROFILE: { path: "/user/profile/", nickname: "Perfil"},
    USER_PROFILE_OVERVIEW: { path: "/user/profile/overview/", nickname: "Geral"},
    USER_PROFILE_PAYMENTS: { path: "/user/profile/payments/", nickname: "Pagamentos"},
    USER_PROFILE_CONFIGURATION: { path: "/user/profile/configuration/", nickname: "Configurações"},
    USER_PROFILE_CONFIGURATION_SUBMIT: { path: "/user/profile/configuration/submit/", nickname: "Configurações"},
    USER_PROFILE_CHARACTERS: { path: "/user/profile/characters/", nickname: "Personagens"},
    USER_PROFILE_CHARACTERS_CREATE: { path: "/user/profile/characters/create/", nickname: "Personagens"},
    USER_PROFILE_CHARACTERS_CREATE_SUBMIT: { path: "/user/profile/characters/create/submit/", nickname: "Personagens"},
    USER_PROFILE_CHARACTERS_UPDATE: { path: "/user/profile/characters/update/", nickname: "Personagens"},
    USER_PROFILE_CHARACTERS_UPDATE_SUBMIT: { path: "/user/profile/characters/update/submit/", nickname: "Personagens"},
    USER_PROFILE_AFFILIATED: { path: "/user/profile/affiliated/", nickname: "Afiliado"},
    USER_PROFILE_IMAGES: { path: "/user/profile/images/", nickname: "Imagens"},
    USER_PROFILE_IMAGES_SUBMIT: { path: "/user/profile/images/submit/", nickname: "Imagens"},
    USER_PROFILE_VIDEOS: { path: "/user/profile/videos/", nickname: "Videos"},
    USER_PROFILE_VIDEOS_SUBMIT: { path: "/user/profile/videos/submit/", nickname: "Videos"},
    USER_ADMIN_PANEL: { path: "/user/admin_panel/", nickname: "Admin Panel"},
    USER_ADMIN_PANEL_OVERVIEW: { path: "/user/admin_panel/overview/", nickname: "Geral"},
    USER_ADMIN_PANEL_LIBRARYANDMAP: { path: "/user/admin_panel/libraryandmap/", nickname: "Biblioteca e Mapa"},
    USER_ADMIN_PANEL_LIBRARYANDMAP_LANGUAGES: { path: "/user/admin_panel/libraryandmap/languages/", nickname: "B & M - Idiomas"},
    USER_ADMIN_PANEL_LIBRARYANDMAP_LANGUAGES_CREATE_SUBMIT: { path: "/user/admin_panel/libraryandmap/languages/create/submit/", nickname: "B & M - Idiomas"},
    USER_ADMIN_PANEL_LIBRARYANDMAP_LANGUAGES_UPDATE_SUBMIT: { path: "/user/admin_panel/libraryandmap/languages/update/submit/", nickname: "B & M - Idiomas"},
    USER_ADMIN_PANEL_LIBRARYANDMAP_ICONS: { path: "/user/admin_panel/libraryandmap/icons/", nickname: "B & M - Ícones"},
    USER_ADMIN_PANEL_LIBRARYANDMAP_ICONS_CREATE_SUBMIT: { path: "/user/admin_panel/libraryandmap/icons/create/submit/", nickname: "B & M - Ícones"},
    USER_ADMIN_PANEL_LIBRARYANDMAP_ICONS_UPDATE_SUBMIT: { path: "/user/admin_panel/libraryandmap/icons/update/submit/", nickname: "B & M - Ícones"},
    USER_ADMIN_PANEL_LIBRARYANDMAP_LOCATIONS: { path: "/user/admin_panel/libraryandmap/locations/", nickname: "B & M - Locais"},
    USER_ADMIN_PANEL_LIBRARYANDMAP_LOCATIONS_CREATE_SUBMIT: { path: "/user/admin_panel/libraryandmap/locations/create/submit/", nickname: "B & M - Locais"},
    USER_ADMIN_PANEL_LIBRARYANDMAP_LOCATIONS_UPDATE_SUBMIT: { path: "/user/admin_panel/libraryandmap/locations/update/submit/", nickname: "B & M - Locais"},    
    USER_ADMIN_PANEL_LIBRARYANDMAP_TRAITS: { path: "/user/admin_panel/libraryandmap/traits/", nickname: "B & M - Características"},
    USER_ADMIN_PANEL_LIBRARYANDMAP_TRAITS_CREATE_SUBMIT: { path: "/user/admin_panel/libraryandmap/traits/create/submit/", nickname: "B & M - Características"},
    USER_ADMIN_PANEL_LIBRARYANDMAP_TRAITS_UPDATE_SUBMIT: { path: "/user/admin_panel/libraryandmap/traits/update/submit/", nickname: "B & M - Características"},
    USER_ADMIN_PANEL_LIBRARYANDMAP_EVENTS: { path: "/user/admin_panel/libraryandmap/events/", nickname: "B & M - Eventos"},
    USER_ADMIN_PANEL_LIBRARYANDMAP_EVENTS_CREATE_SUBMIT: { path: "/user/admin_panel/libraryandmap/events/create/submit/", nickname: "B & M - Eventos"},
    USER_ADMIN_PANEL_LIBRARYANDMAP_EVENTS_UPDATE_SUBMIT: { path: "/user/admin_panel/libraryandmap/events/update/submit/", nickname: "B & M - Eventos"},
    USER_ADMIN_PANEL_LIBRARYANDMAP_NATURES: { path: "/user/admin_panel/libraryandmap/natures/", nickname: "B & M - Naturezas"},
    USER_ADMIN_PANEL_LIBRARYANDMAP_NATURES_CREATE_SUBMIT: { path: "/user/admin_panel/libraryandmap/natures/create/submit/", nickname: "B & M - Naturezas"},
    USER_ADMIN_PANEL_LIBRARYANDMAP_NATURES_UPDATE_SUBMIT: { path: "/user/admin_panel/libraryandmap/natures/update/submit/", nickname: "B & M - Naturezas"},
    USER_ADMIN_PANEL_LIBRARYANDMAP_NPCS: { path: "/user/admin_panel/libraryandmap/npcs/", nickname: "B & M - NPCs"},
    USER_ADMIN_PANEL_LIBRARYANDMAP_NPCS_CREATE_SUBMIT: { path: "/user/admin_panel/libraryandmap/npcs/create/submit/", nickname: "B & M - NPCs"},
    USER_ADMIN_PANEL_LIBRARYANDMAP_NPCS_UPDATE_SUBMIT: { path: "/user/admin_panel/libraryandmap/npcs/update/submit/", nickname: "B & M - NPCs"},
    USER_ADMIN_PANEL_LIBRARYANDMAP_QUESTS: { path: "/user/admin_panel/libraryandmap/quests/", nickname: "B & M - Missões"},
    USER_ADMIN_PANEL_LIBRARYANDMAP_QUESTS_CREATE_SUBMIT: { path: "/user/admin_panel/libraryandmap/quests/create/submit/", nickname: "B & M - Missões"},
    USER_ADMIN_PANEL_LIBRARYANDMAP_QUESTS_UPDATE_SUBMIT: { path: "/user/admin_panel/libraryandmap/quests/update/submit/", nickname: "B & M - Missões"},
    USER_ADMIN_PANEL_LIBRARYANDMAP_ABILITIES: { path: "/user/admin_panel/libraryandmap/abilities/", nickname: "B & M - Habilidades"},
    USER_ADMIN_PANEL_LIBRARYANDMAP_ABILITIES_CREATE_SUBMIT: { path: "/user/admin_panel/libraryandmap/abilities/create/submit/", nickname: "B & M - Habilidades"},
    USER_ADMIN_PANEL_LIBRARYANDMAP_ABILITIES_UPDATE_SUBMIT: { path: "/user/admin_panel/libraryandmap/abilities/update/submit/", nickname: "B & M - Habilidades"},
    USER_ADMIN_PANEL_LIBRARYANDMAP_MONSTERS: { path: "/user/admin_panel/libraryandmap/monsters/", nickname: "B & M - Monstros"},
    USER_ADMIN_PANEL_LIBRARYANDMAP_MONSTERS_CREATE_SUBMIT: { path: "/user/admin_panel/libraryandmap/monsters/create/submit/", nickname: "B & M - Monstros"},
    USER_ADMIN_PANEL_LIBRARYANDMAP_MONSTERS_UPDATE_SUBMIT: { path: "/user/admin_panel/libraryandmap/monsters/update/submit/", nickname: "B & M - Monstros"},
    USER_ADMIN_PANEL_LIBRARYANDMAP_ITEMCATEGORIES: { path: "/user/admin_panel/libraryandmap/itemcategories/", nickname: "B & M - Categorias de Itens"},
    USER_ADMIN_PANEL_LIBRARYANDMAP_ITEMCATEGORIES_CREATE_SUBMIT: { path: "/user/admin_panel/libraryandmap/itemcategories/create/submit/", nickname: "B & M - Categorias de Itens"},
    USER_ADMIN_PANEL_LIBRARYANDMAP_ITEMCATEGORIES_UPDATE_SUBMIT: { path: "/user/admin_panel/libraryandmap/itemcategories/update/submit/", nickname: "B & M - Categorias de Itens"},
    USER_ADMIN_PANEL_LIBRARYANDMAP_ITEMS: { path: "/user/admin_panel/libraryandmap/items/", nickname: "B & M - Itens"},
    USER_ADMIN_PANEL_LIBRARYANDMAP_ITEMS_CREATE_SUBMIT: { path: "/user/admin_panel/libraryandmap/items/create/submit/", nickname: "B & M - Itens"},
    USER_ADMIN_PANEL_LIBRARYANDMAP_ITEMS_UPDATE_SUBMIT: { path: "/user/admin_panel/libraryandmap/items/update/submit/", nickname: "B & M - Itens"},
    USER_ADMIN_PANEL_NEWS: { path: "/user/admin_panel/news/", nickname: "Notícias"},
    USER_ADMIN_PANEL_NEWS_CREATE_SUBMIT: { path: "/user/admin_panel/news/create/submit/", nickname: "Notícias"},
    USER_ADMIN_PANEL_NEWS_UPDATE_SUBMIT: { path: "/user/admin_panel/news/update/submit/", nickname: "Notícias"},
}

export default ROUTES